### ISSUE TITLE
Feature request - request rate

### ISSUE THREAD

**Issue by jangaraj** [cavaliercoder/zabbix_agent_bench#1]
Hi Ryan,

Could you provide also some benchmark performance statistic (e.g. request rate) please?

I've published something similar in python: https://github.com/jangaraj/zabbix-agent-stress-test

**Comment by cavaliercoder** [comment]
Hi Jan, I haven't added any logic yet to output performance stats but I will shortly and I'll get back to you. The initial challenge for this project was to hammer libzbxpgsql with concurrent requests to see if I could make it leak or segfault. I also needed something to dynamically expand discovery rules at runtime.

I did see your project and hoped to contribute but I am completely unfamiliar with Python and needed something up and running quickly.

**Comment by cavaliercoder** [comment]
I've added some basic statistics collection to my tool.
Using the included list of Linux agent keys I get:

```
Finished! Processed 155525 values across 50 threads in 30.102567695s (5166.502791 NVPS)
```

Using just `agent.ping` I get:

```
Finished! Processed 318553 values across 50 threads in 30.001994515s (10617.727426 NVPS)
```

This is on my 1 vCPU, 512MB Vagrant box. I found 50 threads (ala Goroutines) was the sweet spot for performance. Goroutines behave differently to typical pthreads however...

**Comment by cavaliercoder** [comment]
Clicked 'Close' inadvertently. Please let me know if you need anything further.

**Comment by jangaraj** [comment]
Perfect. Thx.

How did you get 10k nvps?

```
# VM: 4CPU, 8GB RAM; zabbix_agentd with 50 agents
./zabbix_agent_bench -key="agent.ping" -timelimit=30 -threads=50
Finished! Processed 153526 values across 50 threads in 30.010118389s (5115.807876 NVPS)
# VM: 4CPU, 8GB RAM; zabbix_agentd with 5 agents
Finished! Processed 211840 values across 50 threads in 30.005902318s (7059.944332 NVPS)
```

**Comment by cavaliercoder** [comment]
I'm not having any luck reproducing it on my macbook at home. Only getting 4000. I've tried agent v2.2.8 and v2.4.4 with similar results.
I'll run it again tomorrow on my work iMac and confirm.

``` bash
# VM: 1CPU, 512MB RAM, zabbix_agentd v2.4.4 with 3 agents
[vagrant@localhost zabbix_agent_bench]$ ./zabbix_agent_bench -key agent.ping -timelimit 30 -threads 50
Testing 1 keys across 50 threads...
agent.ping :    132267  0   0

=== Totals ===

Total values processed:     132267
Total unsupported values:   0
Total transport errors:     0
Total key list iterations:  132267

Finished! Processed 132267 values across 50 threads in 30.014207922s (4406.812945 NVPS)
```

**Comment by cavaliercoder** [comment]
So... testing from my iMac at work... big difference. My Macbook at home is a 2010 i7

``` bash
# 1 CPU, 512MB VM on i5 3.2GHz iMac, zabbix_agentd v2.4.4
$ ./zabbix_agent_bench -key agent.ping -timelimit 30 -threads 50
Testing 1 keys across 50 threads...
agent.ping :    309652  0   0

=== Totals ===

Total values processed:     309652
Total unsupported values:   0
Total transport errors:     0
Total key list iterations:  309652

Finished! Processed 309652 values across 50 threads in 30.002583609s (10320.844499 NVPS)
```

`/proc/cpuinfo`:

```
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 60
model name  : Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
stepping    : 3
microcode   : 0x19
cpu MHz     : 3078.198
cache size  : 6144 KB
physical id : 0
siblings    : 1
core id     : 0
cpu cores   : 1
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 5
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl pni monitor ssse3 lahf_lm
bogomips    : 6156.39
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

**Comment by jangaraj** [comment]
OK, it's CPU. Thx Ryan.
