### ISSUE TITLE
If agent item key contains a % character the standard output is messed up (not verbose section).

### ISSUE THREAD

**Issue by jamescook000** [cavaliercoder/zabbix_agent_bench#2]
The following is the keys configuration file:
# Keys

eventlog[System,,"Warning|Error|Critical",Zabbix Agent,,,]
perf_counter["\Process(zabbix_agentd)\% Privileged Time"]
perf_counter["\Process(zabbix_agentd)\% Processor Time"]
perf_counter["\Process(zabbix_agentd)\% User Time"]
perf_counter["\Process(zabbix_agentd)\Creating Process ID"]
perf_counter["\Process(zabbix_agentd)\Elapsed Time"]
perf_counter["\Process(zabbix_agentd)\Handle Count"]
perf_counter["\Process(zabbix_agentd)\ID Process"]
perf_counter["\Process(zabbix_agentd)\IO Data Bytes/sec"]
perf_counter["\Process(zabbix_agentd)\IO Data Operations/sec"]
perf_counter["\Process(zabbix_agentd)\IO Other Bytes/sec"]
perf_counter["\Process(zabbix_agentd)\IO Other Operations/sec"]
perf_counter["\Process(zabbix_agentd)\IO Read Bytes/sec"]
perf_counter["\Process(zabbix_agentd)\IO Read Operations/sec"]
perf_counter["\Process(zabbix_agentd)\IO Write Bytes/sec"]
perf_counter["\Process(zabbix_agentd)\IO Write Operations/sec"]
perf_counter["\Process(zabbix_agentd)\Page Faults/sec"]
perf_counter["\Process(zabbix_agentd)\Page File Bytes"]
perf_counter["\Process(zabbix_agentd)\Page File Bytes Peak"]
perf_counter["\Process(zabbix_agentd)\Pool Nonpaged Bytes"]
perf_counter["\Process(zabbix_agentd)\Pool Paged Bytes"]
perf_counter["\Process(zabbix_agentd)\Priority Base"]
perf_counter["\Process(zabbix_agentd)\Private Bytes"]
perf_counter["\Process(zabbix_agentd)\Thread Count"]
perf_counter["\Process(zabbix_agentd)\Virtual Bytes"]
perf_counter["\Process(zabbix_agentd)\Virtual Bytes Peak"]
perf_counter["\Process(zabbix_agentd)\Working Set"]
perf_counter["\Process(zabbix_agentd)\Working Set - Private"]
perf_counter["\Process(zabbix_agentd)\Working Set Peak"]

This is the verbose output:
# ./zabbix_agent_bench -host=10.5.9.39 -threads=1 -limit=1 -keys=./keys/Template\ Zabbix\ Agent\ -\ Windows.keys -verbose

Testing 29 keys across 1 threads...
[item] eventlog[System,,"Warning|Error|Critical",Zabbix Agent,,,]: ZBX_NOTSUPPORTEDAccessible only as active check.
[item] perf_counter["\Process(zabbix_agentd)\% Privileged Time"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\% Processor Time"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\% User Time"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\Creating Process ID"]: 468.000000
[item] perf_counter["\Process(zabbix_agentd)\Elapsed Time"]: 7285.248998
[item] perf_counter["\Process(zabbix_agentd)\Handle Count"]: 458.000000
[item] perf_counter["\Process(zabbix_agentd)\ID Process"]: 6564.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Data Bytes/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Data Operations/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Other Bytes/sec"]: 1994.828356
[item] perf_counter["\Process(zabbix_agentd)\IO Other Operations/sec"]: 34.996989
[item] perf_counter["\Process(zabbix_agentd)\IO Read Bytes/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Read Operations/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Write Bytes/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\IO Write Operations/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\Page Faults/sec"]: 0.000000
[item] perf_counter["\Process(zabbix_agentd)\Page File Bytes"]: 11231232.000000
[item] perf_counter["\Process(zabbix_agentd)\Page File Bytes Peak"]: 11231232.000000
[item] perf_counter["\Process(zabbix_agentd)\Pool Nonpaged Bytes"]: 46968.000000
[item] perf_counter["\Process(zabbix_agentd)\Pool Paged Bytes"]: 64532.000000
[item] perf_counter["\Process(zabbix_agentd)\Priority Base"]: 8.000000
[item] perf_counter["\Process(zabbix_agentd)\Private Bytes"]: 11231232.000000
[item] perf_counter["\Process(zabbix_agentd)\Thread Count"]: 57.000000
[item] perf_counter["\Process(zabbix_agentd)\Virtual Bytes"]: 104140800.000000
[item] perf_counter["\Process(zabbix_agentd)\Virtual Bytes Peak"]: 104140800.000000
[item] perf_counter["\Process(zabbix_agentd)\Working Set"]: 13565952.000000
[item] perf_counter["\Process(zabbix_agentd)\Working Set - Private"]: ZBX_NOTSUPPORTEDCannot obtain performance information from collector.
[item] perf_counter["\Process(zabbix_agentd)\Working Set Peak"]: 13565952.000000

This is the standard output:

eventlog[System,,"Warning|Error|Critical",Zabbix Agent,,,]      :       0       1       0
perf_counter["\Process(zabbix_agentd)\%!P(MISSING)rivileged Time"]       :      1       0       0
perf_counter["\Process(zabbix_agentd)\%!P(MISSING)rocessor Time"]        :      1       0       0
perf_counter["\Process(zabbix_agentd)\%!U(MISSING)ser Time"]             :      1       0       0
perf_counter["\Process(zabbix_agentd)\Creating Process ID"]     :       1       0       0
perf_counter["\Process(zabbix_agentd)\Elapsed Time"]            :       1       0       0
perf_counter["\Process(zabbix_agentd)\Handle Count"]            :       1       0       0
perf_counter["\Process(zabbix_agentd)\ID Process"]              :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Data Bytes/sec"]       :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Data Operations/sec"]  :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Other Bytes/sec"]      :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Other Operations/sec"] :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Read Bytes/sec"]       :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Read Operations/sec"]  :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Write Bytes/sec"]      :       1       0       0
perf_counter["\Process(zabbix_agentd)\IO Write Operations/sec"] :       1       0       0
perf_counter["\Process(zabbix_agentd)\Page Faults/sec"]         :       1       0       0
perf_counter["\Process(zabbix_agentd)\Page File Bytes Peak"]    :       1       0       0
perf_counter["\Process(zabbix_agentd)\Page File Bytes"]         :       1       0       0
perf_counter["\Process(zabbix_agentd)\Pool Nonpaged Bytes"]     :       1       0       0
perf_counter["\Process(zabbix_agentd)\Pool Paged Bytes"]        :       1       0       0
perf_counter["\Process(zabbix_agentd)\Priority Base"]           :       1       0       0
perf_counter["\Process(zabbix_agentd)\Private Bytes"]           :       1       0       0
perf_counter["\Process(zabbix_agentd)\Thread Count"]            :       1       0       0
perf_counter["\Process(zabbix_agentd)\Virtual Bytes Peak"]      :       1       0       0
perf_counter["\Process(zabbix_agentd)\Virtual Bytes"]           :       1       0       0
perf_counter["\Process(zabbix_agentd)\Working Set - Private"]   :       0       1       0
perf_counter["\Process(zabbix_agentd)\Working Set Peak"]        :       1       0       0
perf_counter["\Process(zabbix_agentd)\Working Set"]             :       1       0       0

=== Totals ===

Total values processed:         29
Total unsupported values:       2
Total transport errors:         0
Total key list iterations:      1

Finished! Processed 29 values across 1 threads in 40.232175ms (720.816113 NVPS)

**Comment by cavaliercoder** [comment]
Fixed in a7eede88414fe40adca3d838b95d5189f7791342
