### ISSUE TITLE
Discovery keys items does not display if there are no following seperate unrelated items of any nature.

### ISSUE THREAD

**Issue by jamescook000** [cavaliercoder/zabbix_agent_bench#3]
The following file will not work:
# Network Discovery

ext.nic.discovery[All]
    ext.nic.flag.valid.broadcast.address.set[{#IF_NAME}]

The following file will work:
# Network Discovery

ext.nic.discovery[All]
    ext.nic.flag.valid.broadcast.address.set[{#IF_NAME}]

system.uptime

**Comment by cavaliercoder** [comment]
Fixed in 67d705f83079a8aca8d945cbd2c60d2fe498fff1 (as per #4)
